FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    pipewire-bin libspa-0.2-modules gstreamer1.0-tools gstreamer1.0-pipewire \
    gstreamer1.0-plugins-base dbus pipewire-media-session && rm -rf /var/lib/apt/lists/*
